services:
  api:
    build: .
    ports:
      - "8000:80"
    env_file:
      # load_dotenv isn't run in production
      - .env
    environment:
      # overrides for values set in .env, if required
      USE_TIKA: 1
      TIKA_URL: http://tika:9998
    volumes:
      - ./src:/code/src:rw
      - ./generated:/code/src/resources/generated:rw

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

  tika:
    image: apache/tika
    ports:
      - 9998:9998