"""add_parsed_ipg

Revision ID: 096084611e96
Revises: 1d9095f58579
Create Date: 2024-03-10 16:45:11.834465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "096084611e96"
down_revision = "1d9095f58579"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ipg_pending",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creation_day", sa.Date(), nullable=True),
        sa.Column("file_name", sa.Text(), nullable=True),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ipg_pending_creation_day"), "ipg_pending", ["creation_day"], unique=False)
    op.create_index(op.f("ix_ipg_pending_effective_date"), "ipg_pending", ["effective_date"], unique=False)
    op.create_table(
        "ipg_diffs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("dest_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dest_id"],
            ["ipg.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["ipg.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ipg_diffs_dest_id"), "ipg_diffs", ["dest_id"], unique=False)
    op.create_index(op.f("ix_ipg_diffs_source_id"), "ipg_diffs", ["source_id"], unique=False)
    op.create_table(
        "ipg_diffs_pending",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("dest_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dest_id"],
            ["ipg_pending.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["ipg.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("ipg", sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("ipg", sa.Column("effective_date", sa.Date(), nullable=True))
    op.create_index(op.f("ix_ipg_effective_date"), "ipg", ["effective_date"], unique=False)
    op.create_index(op.f("ix_mtr_diffs_dest_id"), "mtr_diffs", ["dest_id"], unique=False)
    op.create_index(op.f("ix_mtr_diffs_source_id"), "mtr_diffs", ["source_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mtr_diffs_source_id"), table_name="mtr_diffs")
    op.drop_index(op.f("ix_mtr_diffs_dest_id"), table_name="mtr_diffs")
    op.drop_index(op.f("ix_ipg_effective_date"), table_name="ipg")
    op.drop_column("ipg", "effective_date")
    op.drop_column("ipg", "sections")
    op.drop_table("ipg_diffs_pending")
    op.drop_index(op.f("ix_ipg_diffs_source_id"), table_name="ipg_diffs")
    op.drop_index(op.f("ix_ipg_diffs_dest_id"), table_name="ipg_diffs")
    op.drop_table("ipg_diffs")
    op.drop_index(op.f("ix_ipg_pending_effective_date"), table_name="ipg_pending")
    op.drop_index(op.f("ix_ipg_pending_creation_day"), table_name="ipg_pending")
    op.drop_table("ipg_pending")
    # ### end Alembic commands ###
