"""remove_diff_structures

Revision ID: 1d9095f58579
Revises: 496edfc212b3
Create Date: 2023-09-03 10:21:01.493504

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "1d9095f58579"
down_revision = "496edfc212b3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cr_diffs", "changes")
    op.drop_column("cr_diffs", "moves")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cr_diffs", sa.Column("moves", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column(
        "cr_diffs", sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
