"""add_mtr_effective_date

Revision ID: 2839ae5907d0
Revises: 0bc6715a73fd
Create Date: 2022-10-07 11:22:19.043434

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2839ae5907d0"
down_revision = "0bc6715a73fd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mtr", sa.Column("effective_date", sa.Date(), nullable=True))
    op.add_column("mtr_pending", sa.Column("effective_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mtr_pending", "effective_date")
    op.drop_column("mtr", "effective_date")
    # ### end Alembic commands ###
