"""add_mtr_data

Revision ID: 40ed282ffb46
Revises: 0cb715a5aac5
Create Date: 2022-10-06 12:01:52.508611

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "40ed282ffb46"
down_revision = "0cb715a5aac5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mtr", sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mtr", "sections")
    # ### end Alembic commands ###
