"""mtr_diff

Revision ID: 63d295d21692
Revises: 2839ae5907d0
Create Date: 2022-12-15 20:03:43.811023

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "63d295d21692"
down_revision = "2839ae5907d0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mtr_diffs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("dest_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dest_id"],
            ["mtr.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["mtr.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mtr_diffs_pending",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("dest_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dest_id"],
            ["mtr_pending.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["mtr.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mtr_diffs_pending")
    op.drop_table("mtr_diffs")
    # ### end Alembic commands ###
