"""moved_cr

Revision ID: c4db41b6319c
Revises: 63d295d21692
Create Date: 2023-06-12 17:52:09.582704

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "c4db41b6319c"
down_revision = "63d295d21692"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cr_diffs", sa.Column("moves", postgresql.ARRAY(sa.Text(), dimensions=2), nullable=True))
    op.add_column("cr_diffs_pending", sa.Column("moves", postgresql.ARRAY(sa.Text(), dimensions=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cr_diffs_pending", "moves")
    op.drop_column("cr_diffs", "moves")
    # ### end Alembic commands ###
