"""cr_toc

Revision ID: f81d76ccde31
Revises: c4db41b6319c
Create Date: 2023-06-16 19:23:08.671453

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "f81d76ccde31"
down_revision = "c4db41b6319c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cr", sa.Column("toc", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("cr_pending", sa.Column("toc", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cr_pending", "toc")
    op.drop_column("cr", "toc")
    # ### end Alembic commands ###
